### ISSUE TITLE
React Router Linkify component

### ISSUE THREAD

**Issue by antondomratchev** [Hypercontext/linkifyjs#169]
I have a case for mention and hashtags to be linked internally to the app. I am using react router for handling internal links.

Currently `linkifyjs/react` implementation will return `tagElement` returned by the tokenizer which is very convenient, unfortunately that results in `<a>` link which isn't handled by react router and causes a page load for the entire app.

Fortunately the change to use react router links is fairly trivial. It requires a react-router Link component as a dependency and a slight change to `linkify-react.js` file. I've made a clone of that component for a project I am working on and had desired results. 

If this is a considerable feature I am open to making a pull request to  add the additional component.

**Comment by nfrasser** [comment]
Hi @antondomratchev I was able to solve this problem by without any changes to the Linkify code: https://jsfiddle.net/2kbv5rf6/

**Comment by nfrasser** [comment]
The key was to specify the `tagName` option as the custom React element when a mention is encountered:

```js
var options = {
  tagName: {
    mention: () => Link // React Router link component
  }
}
```

Afterwards it was a matter of ensuring the right attributes were specified for the `Link` element.

That said, the solution is a *bit* hacky, so I'd be happy to consider a PR that better allows arbitrary React components to be used for generated links.

**Comment by antondomratchev** [comment]
Very nice @nfrasser! 

I am going to take another look at my implementation and see if we can incorporate custom elements passed into opts which would satisfy my requirements. I will try to have something by EOW.


P.S. I love the tokenizer implementation its a great example of a good abstraction.

**Comment by nfrasser** [comment]
There's a new standard way to do this in the [latest v4 release](https://github.com/Hypercontext/linkifyjs/releases/tag/v4.0.0) with the `render` option. [Docs here](https://linkify.js.org/docs/linkify-react.html#custom-link-components).
