### ISSUE TITLE
Hashtag plugin issue

### ISSUE THREAD

**Issue by stasusov** [Hypercontext/linkifyjs#173]
Hello.
There is a problem with hashtags such as:
# b_day (handles only #b)
# бв (doesn't handle any cyrillic symbols)
# АБВ (same)

Thanks.

**Comment by anebril** [comment]
Similar problem occurred to me. I think that there is more general issue that linkify doesn't support localisations.  It would be nice if there would be possibility to create a plugin with definition of used alphabet.

Meantime I managed to fix the problem by adding special characters into ALPHANUM variable in linkify.js

`var ALPHANUM = '0123456789abcdefghijklmnopqrstuvwxyzáąäéęěíóôúůýčťĺňŕřšž'.split('');`

**Comment by apuntovanini** [comment]
+1

**Comment by niconaso** [comment]
I would be helpfull if you support others characters (spanish, ciriclic,..) in addition to the existing ones

**Comment by nfrasser** [comment]
Fixed in v3
