### ISSUE TITLE
Custom protocols

### ISSUE THREAD

**Issue by offsky** [Hypercontext/linkifyjs#194]
Can we have a way to specify custom url protocols in the config/options for this project?  This would be useful for apps that register unique protocols as a way to launch the app. 

For example: evernote:///view/76136038/s12/4d971333-8b65-45d6-857b-243c850cabf5
http://dev.evernote.com/doc/articles/note_links.php

**Comment by nfrasser** [comment]
[Added in v3](https://linkify.js.org/docs/linkifyjs.html#linkifyregistercustomprotocol-str)
