### ISSUE TITLE
URL not recognized when a German umlaut is first character after protocol

### ISSUE THREAD

**Issue by mythsunwind** [Hypercontext/linkifyjs#204]
öko.de fails and marks only **ko.de**
http://öko.de fails and marks only **ko.de**
http://über.de fails and marks only **ber.de**
https://öko.de fails and marks only **ko.de**
www.öko.de fails completely, does not mark anything as text
http://säfte.de works
http://www.öko.de works
http://www.über.de works

**Comment by nfrasser** [comment]
Hi @mythsunwind, thanks for your patience on this one. Internationalized domain support is officially in development and is now available for preliminary testing the the latest v3.0.0-beta.1. Production release coming soon.

**Comment by nfrasser** [comment]
Fixed in v3
