### ISSUE TITLE
App links in iOS and Android not working properly

### ISSUE THREAD

**Issue by dhavalmotghare** [Hypercontext/linkifyjs#205]
App links like instagram://app or are not working properly. The library seems to be linkifying just the ://app part of the link and clicking on it loads nothing so the web view itself becomes invisible. Either links like this should be ignored and should not have a target or they should redirect to app on the device if present.

Here are a few examples of deeplinks for popular apps on iOS:

Twitter	        twitter://timeline	Opens the Twitter app and links to the user’s timeline
Facebook	fb://profile	        Opens the Facebook app and links to the user’s profile

**Comment by dhavalmotghare** [comment]
A similar issue was logged before https://github.com/SoapBox/linkifyjs/issues/194

**Comment by nfrasser** [comment]
Now possible in v3 with [`linkify.registerCustomProtocol`](https://linkify.js.org/docs/linkifyjs.html#linkifyregistercustomprotocol-str)
