### ISSUE TITLE
linkify  convert any word preceded  by // to a link

### ISSUE THREAD

**Issue by gouzal-pi** [Hypercontext/linkifyjs#206]
Hey, Thanks a lot for this useful plugin. 
I just have an issue, linkify convert any word preceded by // to a link.
for example, those following words will be converted to a link:
//test
//gitHub
//google

is that okey? or did I miss something?
I am using:

- linkify.min.js
- linkify-jquery.min

**Comment by Hongbo-Miao** [comment]
Met same issue.

Sometimes when I have comment by `//` in the content, it will be linkified:

`<p>//something</p>`

will be linkified to

`<a href="//something" target="_blank">//something</a></p>`

which is unexpected.

**Comment by agurtovoy** [comment]
Workaround:

```js
linkifyHtml( text, {
    validate: {
        url: str => str.indexOf( "//" ) !== 0
    }
} );
```

**Comment by nfrasser** [comment]
Fixed in v3
