### ISSUE TITLE
Does not properly linkify URLs with custom protocol fields

### ISSUE THREAD

**Issue by NotAFile** [Hypercontext/linkifyjs#212]
This was originally reported downstream as https://github.com/vector-im/riot-web/issues/5094

When viewing links, of the form protocol://whatever, linkify does not properly highlight the full link

Steps to reproduce

- linkify message with a link with a custom protocol, e.g. aos://151723184:32876:0.75
- Notice that the aos: does not get linkified, only the //151723184:32876:0.75

**Comment by alex-jitbit** [comment]
any plans to consider this?

Would lvoe to see support for `skype:xxx` `git:xxx` `about:xxx` etc

**Comment by mikejzx** [comment]
Would also like to see this implemented, so we can linkify `gopher://` and `gemini://` links :wink:

**Comment by nfrasser** [comment]
Fixed in v3. [See docs for adding custom protocols](https://linkify.js.org/docs/linkifyjs.html#linkifyregistercustomprotocol-str).

**Comment by hkuznetsovb** [comment]
guys, how to add custom protocol for react component? I registered it by using linkify.registerPlugin but <Linkify /> component doesn't recognize new protocol..

**Comment by nfrasser** [comment]
@hkuznetsovb use `linkify.registerCustomProtocol` instead
