### ISSUE TITLE
Hashtags in other languages

### ISSUE THREAD

**Issue by nazarkryp** [Hypercontext/linkifyjs#231]
Could you please add support for other languages?
I can generate link from english text (e.g #linkify). But unable to create one from ukrainian (#україна)

**Comment by origamium** [comment]
+1

**Comment by nfrasser** [comment]
Hi all, thanks for your patience on this one. Internationalized domain support + hashtag is officially in development and is now available for preliminary testing the the latest v3.0.0-beta.1. Production release coming soon.

**Comment by nfrasser** [comment]
Fixed in v3
