### ISSUE TITLE
Cyrillic URL doesn't pass

### ISSUE THREAD

**Issue by ccorcos** [Hypercontext/linkifyjs#251]
This url does not work

https://выставить-счет.рф/blanki/akt/akt-neiskluchitelnie-prava/#akt

However, if you paste it into chrome and the copy it out, it now looks like this:

https://xn----7sbfbqq4deedd2d1bu.xn--p1ai/blanki/akt/akt-neiskluchitelnie-prava/#akt

And that link does work. No idea why though. Any idea what function is doing that escaping?

**Comment by alar1** [comment]
+

**Comment by DominikSerafin** [comment]
@ccorcos AFAIK linkifyjs doesn't support unicode URLs. You would need to use something like [punycode](https://github.com/bestiejs/punycode.js/) to convert it to latin characters version (like the second link).

**Comment by nfrasser** [comment]
Hi all, thanks for your patience on this one. Internationalized domain support is officially in development and is now available for preliminary testing the the latest v3.0.0-beta.1. Production release coming soon.

**Comment by nfrasser** [comment]
Fixed in v3
