### ISSUE TITLE
IP address support

### ISSUE THREAD

**Issue by shrimalmadhur** [Hypercontext/linkifyjs#26]
I guess IP addresses like http://143.345.33.44:8181 should also be supported. Are you guys planning for that?

**Comment by sosoHero** [comment]
When this gets implemented it should exclude addresses reserved for private networks (https://en.wikipedia.org/wiki/IPv4#Private_networks). Looking forward to the addition of this feature.

**Comment by Rejpal** [comment]
it looks to me that IP addresses are implemented already when http:// is before them...

**Comment by herbetom** [comment]
@Rejpal It seems like currenlty only IPv4 Addresses with a http(s) prefix are recognized. IPv6 Support seems to be missing completely:

![image](https://user-images.githubusercontent.com/15121114/147511797-a4a70692-4364-4f3e-b39b-26cba588253b.png)
Tested with the [demo](https://linkify.js.org/#demo) and the following list:

https://1.1.1.1/
https://1.1.1.1:443/
https://[2606:4700:4700::1111]/ 
https://[2606:4700:4700::1111]:443/

Supporting IPv6 (with a http(s) prefix) would be really nice. 
@nfrasser But maybe this should be dealt with in a seperate issue?

**Comment by nfrasser** [comment]
Long overdue but happy to report that bare IPv4 and prefixed IPv6 addresses are now supported in the [latest v4 release](https://github.com/Hypercontext/linkifyjs/releases/tag/v4.0.0) via the `ip` plugin ([docs here](https://linkify.js.org/docs/plugin-ip.html)). Thanks all for your contributions!
