### ISSUE TITLE
Linking arbitrary words

### ISSUE THREAD

**Issue by chrism2671** [Hypercontext/linkifyjs#269]
I'm trying to figure out if I can write a plugin to link arbitrary words/phrases to specific destinations (I can load a json list from the server).

Such a list might have 100+ different words, so I'm wondering if it's possible. I've tried to code this up already with vanilla jQuery, but it's a headache.

In your opinion, is this something that linkify might be retrofitted to do?

**Comment by nfrasser** [comment]
This is now possible with the [latest v4 release](https://github.com/Hypercontext/linkifyjs/releases/tag/v4.0.0) via the [`keyword` plugin](https://linkify.js.org/docs/plugin-keyword.html).
