### ISSUE TITLE
Email detection wrong when prefixed with an '：' character

### ISSUE THREAD

**Issue by PolarizedIons** [Hypercontext/linkifyjs#273]
The Chinese character '：'  looks like a colon + a space, but isn't. When our user, for example, types `Firstname：email.@server.com` linkify incorrectly detects `Firstname：` as part of the email

I would expect it to work the same as `Firstname:email@server.com`, which detects only `email@server.com`

**Comment by tafelnl** [comment]
Hmm, I'm not sure if I agree with this. If you would take this into account within this plugin, you could argue that any character that looks like a punctuation mark would have to be taken into account. I think that's a bit much.

(Besides, if it is _not_ considered a colon anyway, what is it? A p{Letter} character? In that case the regex is actually correct)
