### ISSUE TITLE
Mention Special Characters

### ISSUE THREAD

**Issue by waqasasif9292** [Hypercontext/linkifyjs#284]
When mention with using (ä, ö å) or any special character, the tag gets cut out.

**Comment by waqasd4int** [comment]
is there any progress, please let me know when you will be able to implement this

**Comment by benkeen** [comment]
I'd be very interested in any progress on this too. I've been exploring alternatives to this lib but nothing seems half so convenient. Unfortunately it's rather wreaking havoc with domains with non-latin chars.

**Comment by azhard4int** [comment]
+1

**Comment by timhuebener** [comment]
+1

**Comment by nfrasser** [comment]
Hi all, thanks for your patience on this one. Internationalized mention support is officially in development and is now available for preliminary testing the the latest v3.0.0-beta.1. Production release coming soon.

**Comment by nfrasser** [comment]
Fixed in v3
