### ISSUE TITLE
Typescript options for a clickHandler for React

### ISSUE THREAD

**Issue by LeonY1** [Hypercontext/linkifyjs#292]
Based on the documentation, adding onClick handlers is done through using the attributes field; however, when using TypeScript the type is set to the following:
``` javascript
attributes?: Record<string, string> | ((href: string, type: LinkEntityType) => Record<string, string>) | null;
```

This doesn't allow for there to be an onClick like how it would be in vanilla React. I haven't really checked if this is something that is currently being developed. However, I did want to ask for this support.

Documentation for Linkifyjs 2.1:
``` javascript
let linkProps = {
  onClick: (event) => {
    if (!confirm('Are you sure you want to leave this page?')) {
       event.preventDefault()
    }
  }
};
return <Linkify options={{attributes: linkProps}}>
  ...
</Linkify>;
```

**Comment by piazz** [comment]
Also watching this one. Typescript + React is pretty broken with this currently

**Comment by ogtfaber** [comment]
The onClick event also isn't added to the dom it seems

**Comment by nfrasser** [comment]
Linkify v3 now includes TypeScript definitions that should not break for this. More extensive type definitions are coming in future releases.
