### ISSUE TITLE
 TypeError: Cannot read property 'push' of undefined TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by joaolnpr** [Hypercontext/linkifyjs#301]
Hello

**Linkify v2.1.9 and v2.1.8** Is failing parsing some content as show in the attached image, any fix available?

![image](https://user-images.githubusercontent.com/48879345/93873876-5fdaf580-fcca-11ea-828d-025b08e4427d.png)

**Comment by joaolnpr** [comment]
**UPDATE**: I can now confirm the issue is being provoked by character < which is being recognised as a tag.

**Comment by joaolnpr** [comment]
Any fix for this?

**Comment by longprao** [comment]
I got the same issue, if no fix, is there any workaround?

**Comment by nfrasser** [comment]
@joaolnpr apologies for the delay, can you paste in some text that I can use to reproduce this issue? I can't copy/paste from this image

**Comment by nfrasser** [comment]
A potential workaround: If you know the string you are trying to parse does not have any HTML in it, use the `linkifyjs/string` interface instead:

```js
import linkifyStr from 'linkifyjs/string';
// ...
linkifyStr(content);
```

**Comment by nfrasser** [comment]
Should be fixed in the latest v3
