### ISSUE TITLE
persian/arabic hashtag

### ISSUE THREAD

**Issue by alirezamaleky** [Hypercontext/linkifyjs#309]
`hashtag` plugin does not support persian/arabic hashtags like: #سلام
please add this feature.

**Comment by nfrasser** [comment]
Hi @alirezamaleky, thanks for reporting this. Internationalized hashtag support is officially in development and is now available for preliminary testing the the latest v3.0.0-beta.1. Production release coming soon.

**Comment by nfrasser** [comment]
If you can, please try out that release and see if you can find any bugs.

**Comment by nfrasser** [comment]
Fixed in v3
