### ISSUE TITLE
An easy way to compatible special characters in mention and hashtag

### ISSUE THREAD

**Issue by smilecc** [Hypercontext/linkifyjs#312]
By reading the source code, I found an easy way to compatible special characters in mention.

Although I'm not sure, it's strong or not, however, It's working.

## How to do (Only Mention)

Talk is cheap, the code:

```typescript
import * as linkify from 'linkifyjs';
import { DOMAIN } from 'linkifyjs/lib/linkify/core/tokens/text';

const { scanner } = (linkify as any);
scanner.start.on(/[\u2E80-\u9FFF]/, new scanner.State(DOMAIN));
```

`/[\u2E80-\u9FFF]/` is the RegExp of Chinese, Japanese, and Korean character sets, replace them with what you want at will.

### Before
![before](https://user-images.githubusercontent.com/7179432/107357912-9aeb9300-6aca-11eb-8779-b4e0e3d82702.png)

### After
![after](https://user-images.githubusercontent.com/7179432/107357926-9fb04700-6aca-11eb-8b08-f8fd46b3225c.png)

## Why?

This library work through character matching and state transition.

Mention plugin to tell the core how to match and state transfer. When the next state is null, the matching is finished.

But the character sets of this library did not contain what we needed (some special chars), **Because this library default just have ASCII chars**. so it's always null.

So just add the character set we need, it seems to work well.

**Comment by smilecc** [comment]
I hope this can help you
@alirezamaleky @timhuebener

**Comment by smilecc** [comment]
## Hashtag Support

Compared to mention, the method of supporting hashtag is HACK. Because `S_DOMAIN` is not export from `scanner.js`.

So I had to search the whole state tree.

**If you used this code, you don't need to use `Only Mention`'s code.**

```typescript
import * as linkify from 'linkifyjs';
import { DOMAIN } from 'linkifyjs/lib/linkify/core/tokens/text';

const ALPHANUM = '0123456789abcdefghijklmnopqrstuvwxyz';
const APPEND_REG = /[\u2E80-\u9FFF]/;

const scanner = (linkify as any).scanner;
const stateDomain = new scanner.State(DOMAIN);
stateDomain.processed = true;
stateDomain
  .on(ALPHANUM.split(''), stateDomain)
  .on(APPEND_REG, stateDomain);

function deepSet(deep: number, state: any) {
  if (deep > 3) {
    return;
  }

  state.on(APPEND_REG, stateDomain);
  state.processed = true;

  for (const item of state.j) {
    const [keyword, nextState] = item;
    if (!nextState.processed && ALPHANUM.includes(keyword)) {
      deepSet(deep + 1, nextState);
    }
  }

  return state;
}

deepSet(0, scanner.start);
```

### Before
![before](https://user-images.githubusercontent.com/7179432/107367076-c6747a80-6ad6-11eb-9b9d-be7aeb1a7581.png)

### After
![after](https://user-images.githubusercontent.com/7179432/107367091-cb392e80-6ad6-11eb-9d3c-2afda8239922.png)

**Comment by smilecc** [comment]
I hope this can help you
@alirezamaleky @timhuebener

**Comment by nfrasser** [comment]
@smilecc, thanks so much for writing this up! 

FYI, internationalized mention and hashtag support is getting added to linkify 3.0 and is now available for preliminary testing in the latest v3.0.0-beta.1. Production release coming soon.

**Comment by nfrasser** [comment]
Fixed in v3

**Comment by toger5** [comment]
How is this supposed to work now? I cannot get a `tt` with a character array or an regex expression to work

**Comment by nfrasser** [comment]
@toger5 see details here: https://github.com/Hypercontext/linkifyjs/issues/167#issuecomment-1018668663
