### ISSUE TITLE
Question - white space on link

### ISSUE THREAD

**Issue by adielsh** [Hypercontext/linkifyjs#314]
Hi,

When I write for example something like that:
linkifyStr("http://someLinkWith space.pdf", {})

I got link this link: **http://someLinkWith**
And the other part is: **space.pdf** which its not calculated as link.
But I excpected that the link include all the file name include .pdf suffix.

Is it depend on configurations?

Thanks

**Comment by nfrasser** [comment]
White space is not considered a legal URL character (unless encoded, e.g., `%20`). If it were, then simply typing http://someLink would convert the rest of this sentence into link. 

Can you please provide an example of a _real_ URL or domain name contains white space? Ideally one that works when I type it into the browser URL bar.

**Comment by nfrasser** [comment]
Closing as out of scope
