### ISSUE TITLE
Allow options to be passed to find/test/tokenize

### ISSUE THREAD

**Issue by connor4312** [Hypercontext/linkifyjs#317]
I would like the defaultProtocol to be https, but I need to kind of hack around to make this work using find/test/tokenize since they don't take options. It looks like the default options are also not applied to them:

![](https://memes.peet.io/img/21-03-e6b02c04-2a24-4f62-9537-effacab4a16e.png)

**Comment by nfrasser** [comment]
Fixed in v3. `linkify.find` and `linkify.tokenize` now respects `linkify.options.defaultProtocol`. Each token output of `linkify.tokenize` also has a `.toHref(defaultProtocol=options.defaultProtocol)` method
