### ISSUE TITLE
Remove the peer dependencies for react and read-dom

### ISSUE THREAD

**Issue by ryaa** [Hypercontext/linkifyjs#323]
I use this package in ionic/angular project and getting the below warning when install it
```
npm WARN linkifyjs@2.1.9 requires a peer of react@>= 0.14.0 but none is installed. You must install peer dependencies yourself.
npm WARN linkifyjs@2.1.9 requires a peer of react-dom@>= 0.14.0 but none is installed. You must install peer dependencies yourself.
```

My assumption is that the peer dependencies for react and read-dom are not required and can be removed to avoid the above warning when the package is used in non react project.

**Comment by nfrasser** [comment]
Hi @ryaa, thanks for reporting. This is coming in to final v3.0 release

**Comment by nfrasser** [comment]
Fixed in v3 - react component is not available in separate `linkify-react` package.
