### ISSUE TITLE
HTTP Basic Auth support broken - loses casing

### ISSUE THREAD

**Issue by t3chguy** [Hypercontext/linkifyjs#326]
The username gets lowercased against the spec 

https://tools.ietf.org/html/rfc7617#section-2.1
https://tools.ietf.org/html/rfc7613#section-3.3

> Case-Mapping Rule: Uppercase and titlecase characters MUST NOT be
mapped to their lowercase equivalents; see further discussion in
Section 3.4.

See https://github.com/vector-im/element-web/issues/16825 for more details

Reproduction:

https://soapbox.github.io/linkifyjs/

Enter `https://Foo:Bar@Test.com/FooBar` and linkify, the link points to `https://foo:Bar@test.com/FooBar` and breaks the auth.

**Comment by nfrasser** [comment]
Fixed in v3
