### ISSUE TITLE
`target` option in linkify options not working

### ISSUE THREAD

**Issue by hrichiksite** [Hypercontext/linkifyjs#331]
I tried with this code as per the docs, but it doesn't seem to work

Input : `Just a test account, check out @Hrichik for stuff, also don't check out https://test.link/get-no-dogecoin`

Output : `Just a test account, check out <a id="mention" rel="noopener noreferrer" class="heading-3 link font-bold" href="/Hrichik">@Hrichik</a> for stuff, also don't check out <a id="link" rel="noopener noreferrer" class="heading-3 link font-bold" href="https://test.link/get-no-dogecoin">https://test.link/get-no-dogecoin</a>` ( No target attribute )

My code :
```
linkifyHtml(bio, {
        defaultProtocol: 'https',
        className: 'heading-3 link font-bold',
        format: {
          url: function (value) {
            return value.length > 40 ? value.slice(0, 40) + '…' : value
          }
        },
        attributes: function (href, type) {
          at = {
            rel: 'noopener noreferrer '
          }
          if(type === 'mention'){
            at.id = 'mention'
            at.targete = '_blank'
            at['target'] = '_blank'
            return at;
          } else {
            at.id = 'link'
            return at;
          }
        },
        target: {
          url: '_blank'
        },
      });
```

**Comment by zyll** [comment]
https://github.com/Soapbox/linkifyjs/blob/f38f1e287d4d914b7d6119c4313a4e99e2699d49/test/spec/linkify-string-test.js#L26 suggest that you can target _blank like with `linkifyHtml(bio, { target: '_blank' })`

**Comment by nfrasser** [comment]
Should be working in the latest v3, careful not to override the `target` in your `attributes` function
