### ISSUE TITLE
[Bug] Linkify cause jest to break

### ISSUE THREAD

**Issue by adamchenwei** [Hypercontext/linkifyjs#333]
anyone encounter similar issue?
using a asset transformer will result in `TypeError: Super expression must either be null or a function, not undefined`
(more detail to come as I dig into this lib further)
* I looked into almost all first page posts on google related to these error msg btw. no resolutions
* also the Linkify was wrapping `import { DialogContent } from '@material-ui/core';`
![Screen Shot 2021-06-03 at 10 28 18 AM](https://user-images.githubusercontent.com/4201698/120661638-74c17880-c456-11eb-8e8c-eefcf5b52f3b.png)

☝️  that's pretty much what I see when I start running the jest integration test I am writing

Note: I initially mentioned about image src because this error won't even get chance to show when the image loading

**Comment by adamchenwei** [comment]
problem starts here where `_React$Component` is undefined. any idea why its throwing here?
@grahammccarthy

**Comment by nfrasser** [comment]
Should be fixed in v3
