### ISSUE TITLE
Linkify not working with greater and lower characters

### ISSUE THREAD

**Issue by cristiann190** [Hypercontext/linkifyjs#338]
The linkifyHtml does not work fine with some special characters. 

We get a text from our database and using linkifyHtml we are getting problems with some characters like - or ><.
`<http://nu.nl>
-http://nu.nl-
,http://nu.nl,
.http://nu.nl.
{http://nu.nl}
[http://nu.nl]
'http://nu.nl'
"http://nu.nl"
`
This is the original list, the first 2 doesn't work. 
Then in our case, we have stored in database:
We store the values sanitized.

`&lt;http://nu.nl&gt;`

This one it's also failing.

![image](https://user-images.githubusercontent.com/61523813/125767262-d6ca17ea-e5b4-474b-bd62-de028d8027e7.png)

**Comment by nfrasser** [comment]
Hi @cristiann190 , please use [`linkify-string`](https://linkify.js.org/docs/linkify-string.html) instead of `linkify-html` for this case

**Comment by cristiann190** [comment]
Hi @nfrasser I tried with string option, but I still get weird values, and also for a link pasted in the box the result now its not good. So not a good option. 
![image](https://user-images.githubusercontent.com/61523813/133747948-25e2eace-7633-45d1-8568-8e282d96866c.png)

**Comment by nfrasser** [comment]
Fixes as best as possible in the latest [Linkify v4](https://github.com/Hypercontext/linkifyjs/releases/tag/v4.0.0)
