### ISSUE TITLE
Did not linkify text with below format

### ISSUE THREAD

**Issue by vaishali-shm** [Hypercontext/linkifyjs#340]
I was trying to detect & linkify all present &valid links but came across below scenario where link was not detected, it might not be a common use case but having a portal where it automates social media & counts heavily on links, not being able to preview the same creates problems & gives a gateway for bugs.

<a href=www.apple.com did not result in links.

<a href= www.apple.com **OR** <a href="www.apple.com **OR** <a href='www.apple.com seems to work fine.

Any help will be appreciated.

**Comment by nfrasser** [comment]
Hi @vaishali-shm, are you trying to parse text that contains valid HTML and should be rendered that way? Or does the text happen to look like a bit like HTML? Have you tried [`linkify-html`](https://soapbox.github.io/linkifyjs/docs/linkify-html.html)?

**Comment by wobsoriano** [comment]
> Hi @vaishali-shm, are you trying to parse text that contains valid HTML and should be rendered that way? Or does the text happen to look like a bit like HTML? Have you tried [`linkify-html`](https://soapbox.github.io/linkifyjs/docs/linkify-html.html)?

what happened to linkify-html? Page is 404 and is missing in npmjs

**Comment by nfrasser** [comment]
@wobsoriano `linkify-html` is now back on NPM (due to a publish issue I had to wait 24 hours before re-publishing). Docs are here: https://linkify.js.org/docs/linkify-html.html apologies for the confusion!
