### ISSUE TITLE
Hashtags cut off after underscore 

### ISSUE THREAD

**Issue by David-337** [Hypercontext/linkifyjs#342]
Hi!
This is a great plugin that has saved us tons of time, however our users discovered this issue

These two hashtags are linkified on Twitter:
`#bug_test`
`#bug__test`

However linkfiyjs captures them as
`#bug_`
`#bug__`

It seems that linkifyjs allows trailing underscores but stops linkifying at any non-underscore character following an underscore

**Comment by nfrasser** [comment]
Fixed in v3.0.2
