### ISSUE TITLE
Module not found: Can't resolve 'linkifyjs/lib/plugin/hashtag'

### ISSUE THREAD

**Issue by bigint** [Hypercontext/linkifyjs#348]
![image](https://user-images.githubusercontent.com/69431456/133804705-594ddbeb-a50f-44a7-bea2-356f39b6e5a2.png)

/cc @nfrasser

**Comment by nfrasser** [comment]
Fixed in v3.0.2, sorry about that!

**Comment by bigint** [comment]
No worries, waiting for the release 🤞🏻

**Comment by bigint** [comment]
@nfrasser any updates? waiting for the release 🙇🏻

**Comment by nfrasser** [comment]
@bigint you just have to update the `linkify-plugin-hashtag` plug-in no need to update `linkifyjs`
