### ISSUE TITLE
linkifyHtml: issue with specific html-escaped links

### ISSUE THREAD

**Issue by phoneyman** [Hypercontext/linkifyjs#350]
Using linkifyHtml on an escaped string produces incorrect output. EG: linkifyHtml() called on the string '&quot;http://google.com&quot;' produces the following output: '&quot;<a href="http://google.com&quot" class="linkified" target="_blank">http://google.com&quot</a>;' which renders as "http://google.com";

The call in the code is:
var options = {/* */};
final = linkifyHtml('&quot;http://google.com&quot;', options);

**Comment by nfrasser** [comment]
Fixed in the latest [v4 release](https://github.com/Hypercontext/linkifyjs/releases/tag/v4.0.0).
