### ISSUE TITLE
Allow `~` as leading e-mail character

### ISSUE THREAD

**Issue by emersion** [Hypercontext/linkifyjs#358]
Currently, linkifyjs accepts `a~b@example.org` as an email address, but not `~a@example.org`.

FWIW, the `~` character is used in https://lists.sr.ht addresses, e.g. `~emersion/soju-dev@lists.sr.ht`.

**Comment by nfrasser** [comment]
Now supported in the latest [v4 release](https://github.com/Hypercontext/linkifyjs/releases/tag/v4.0.0).

**Comment by emersion** [comment]
Thanks!
