### ISSUE TITLE
Adjust documentation around XSS

### ISSUE THREAD

**Issue by kylemh** [Hypercontext/linkifyjs#359]
On the [XSS page](https://linkify.js.org/docs/xss.html), I see:

> Other interfaces that work with the DOM, including linkify-element, linkify-jquery, and linkify-react, only apply to text-nodes. By design, they will not generate any non-anchor tags that are not already in the DOM.

and the wording confused me a bit. I _BELIEVE_ it's being said that those libraries _will_ essentially sanitize the strings by only operating on text nodes. In general, I feel like this page should read like:

- linkifyHtml() does not sanitize the parsed string.
- linkifyString() and linkify-element, linkify-jquery, and linkify-react DO sanitize the parsed string.
- Our sanitization process only prevents basic HTML insertion. We do not approve-list or ban-list any links.

**Comment by nfrasser** [comment]
Revamped XSS docs based on your suggestion, thanks @kylemh! If you have any additional notes, feel free to open a pull request against the [`gh-pages` branch](https://github.com/Hypercontext/linkifyjs/tree/gh-pages).
