### ISSUE TITLE
the string 'fasfafhttp://google.com' recognition error

### ISSUE THREAD

**Issue by wulisensen** [Hypercontext/linkifyjs#360]
result:
'fasfafhttp://google.com'  => 'fasfafhttp://' + <a>google.com</a>

i want
'fasfafhttp://google.com'  => 'fasfaf' + <a>http://google.com</a>:

version 3.0.3

**Comment by varunsrin** [comment]
@nfrasser are you considering fixing this for v4? or is this desired behavior for Linkify going forward?

FWIW, a lot of user input text fields suffer from this problem, so it's unfortunately something we have to deal with often and it was great when linkify handled it automatically.

**Comment by nfrasser** [comment]
> are you considering fixing this for v4? or is this desired behavior for Linkify going forward?

Unfortunately no, it would require a complete rethinking of the internal parsing system and honestly I don't have the necessary language processing knowledge to do it

>  it was great when linkify handled it automatically.

I don't recall that linkify was ever able to handle these cases, except perhaps years ago in V1. Do you know the last version of linkify where this worked?
