### ISSUE TITLE
Specify module entry point in package.json

### ISSUE THREAD

**Issue by palash2601** [Hypercontext/linkifyjs#361]
When using linkifyjs as a transitive dependency, below error is thrown

![image](https://user-images.githubusercontent.com/14163870/141066028-61ca248e-19d1-49c9-a128-0c48d1b27a4e.png)

```
import { find } from 'linkifyjs';
```

This can be resolved by adding entry point for ESM in package.json which build tools like Rollup etc.. can use to resolve the entry point.

Other packages also handle the entry points in similar way:
https://github.com/ueberdosis/tiptap/blob/main/packages/extension-link/package.json#L17

**Comment by nfrasser** [comment]
Fixed in v3.0.4
