### ISSUE TITLE
Linkify html converts &lt; to <

### ISSUE THREAD

**Issue by richie-south** [Hypercontext/linkifyjs#362]
Linkify converts `&lt;`to `<` by default. 
Our server sends html but sanitise script tags by replacing `<` with `&lt;` This so we can render the html as html but only display scripts as texts instead of xxs ourself. But with latest linkify-html v3 it converts `&lt;` to `<`which creates a functional script tag. I don't see any working option to ignore `&lt;` or am i missing something? 

Example [replit](https://replit.com/@richie_south/LatestVerifiableUpgrade#index.js)

**Comment by nfrasser** [comment]
Fixed in the latest [v4 release](https://github.com/Hypercontext/linkifyjs/releases/tag/v4.0.0).
