### ISSUE TITLE
truncate option with jquery not working

### ISSUE THREAD

**Issue by dingolino67** [Hypercontext/linkifyjs#367]
Hi, 
I am struggling with the truncate option using the jquery API. I have the 
impression that this option is not at all implemented. Could that be or am I doing something wrong?
In my application the URLs are linkified. Thus I know that the library is working. Just the truncate business is 
not working. Any suggestions?
```
<script src="linkifyjs/linkify.js"></script>
<script src="linkifyjs/linkify-html.js"></script>
<script src="linkifyjs/linkify-jquery.js"></script>

<script>
const options = { truncate:30  };
$("td").linkify(options);     
</script>
```

**Comment by nfrasser** [comment]
Hi @dingolino67, this is a known issue and due to be fixed in the next release. In the meantime, I suggest [the `format` option](https://linkify.js.org/docs/options.html#format) as a workaround
```js
$("td").format({
  format: (value) => {
    if (value.length > 50) {
      return value.slice(0, 50) + '…';
    } else {
      return value;
    }
  }
});
```

**Comment by dingolino67** [comment]
Thanks a lot. That works.

**Comment by nfrasser** [comment]
Fixed in latest [v4 release](https://github.com/Hypercontext/linkifyjs/releases/tag/v4.0.0).
