### ISSUE TITLE
linkify-html tries to parse empty tags

### ISSUE THREAD

**Issue by iskrenvankov** [Hypercontext/linkifyjs#370]
Hi, when using linkify-html I've run into the following issue:

**Example input:** `Foo/Bar <> Zoo/Zar`

**Expected output:** same as the input (no change)

**Observed output:** `Foo/Bar <zoo></zoo>`

**Comment by nfrasser** [comment]
Hi @iskrenvankov, this is an issue with Linkify's HTML parser [simple-html-tokenizer](https://github.com/tildeio/simple-html-tokenizer). I'd suggest filing this issue there or escaping your input before passing it to Linkify:

```js
linkifyHtml(input.replace('<>', '&lg;&gt;'))
```

**Comment by iskrenvankov** [comment]
> 

Hi @nfrasser thanks for the suggestion, in the end I did end up doing precisely that. 
Still, I'll raise it with simple-html-tokenizer.
