### ISSUE TITLE
registerCustomProtocol doesn't linkify without double slashes

### ISSUE THREAD

**Issue by aaronraimist** [Hypercontext/linkifyjs#372]
The description for linkify.registerCustomProtocol says "Linkify will consider any string that begins with the given protocol followed by a : as a URL link" but that doesn't seem to be true. Linkifyjs seems to be looking for `://` after the protocol for it to be considered a link.

URI schemes without an authority component such as `geo:`, `matrix:`, and `xmpp:` don't get linkified.

Here is an example: https://codepen.io/aaronraimist/pen/bGoOXrq. Only `mailto` gets linkified.

```
import * as linkify from "https://cdn.skypack.dev/linkifyjs";
import linkifyStr from "https://cdn.skypack.dev/linkify-string";

linkify.registerCustomProtocol("geo");
linkify.registerCustomProtocol("matrix");
linkify.registerCustomProtocol("xmpp");

createLink("mailto:test@example.com");
createLink("geo:37.786971,-122.399677");
createLink("matrix:r/someroom:example.org");
createLink("xmpp:romeo@montague.net?message");

function createLink(string) {
  console.log(linkifyStr(string));
  console.log(linkify.test(string));
}
```

**Comment by nfrasser** [comment]
Hi @aaronraimist, thanks for reporting. This is a known issue and will be fixed in v4 (#354)

**Comment by toger5** [comment]
when will this be ready?
I am currently adding a custom parser for `matrix:u/...` links. This causes all kinds of issues. Maybe I should open specific issues in what I am running into. This would be really really helpful!

**Comment by nfrasser** [comment]
@toger5 a beta is now available that you can try out:
```
npm install linkifyjs@beta
```

(Requires `@beta` versions of related Linkify plugins and interfaces)

**Comment by nfrasser** [comment]
No timeline yet on a stable release, there's still a few more features that need development

**Comment by nfrasser** [comment]
Fixed in latest v4 release. Have to add a second `true` argument to the `registerCustomPrococol` function call.
