### ISSUE TITLE
Domains that start with schemes should be accepted

### ISSUE THREAD

**Issue by jryans** [Hypercontext/linkifyjs#374]
I recently noticed that domains which start with schemes (e.g. `http`) are currently ignored and not linked.

For example, all of the following should linkify the full text, as they are valid domains:

* http.org
* http-help.org
* http123.org

**Comment by jryans** [comment]
I have already resolved this in a fork of the 4.0 branch. I'm happy to contribute that over here if you'd like.

**Comment by nfrasser** [comment]
Hi @jryans thanks for reporting. This is now fixed in the latest beta release v4.0.0-beta.3

**Comment by jryans** [comment]
Thanks for the quick fix! I have verified that v4.0.0-beta.3 indeed resolves this issue. 😄
