### ISSUE TITLE
Custom protocol with numbers should be allowed

### ISSUE THREAD

**Issue by aaronraimist** [Hypercontext/linkifyjs#377]
Using v4.0.0-beta.4

When attempting to register the custom protocol `openpgp4fpr` (which is a [safelisted scheme](https://html.spec.whatwg.org/multipage/system-state.html#custom-handlers:safelisted-scheme)), Linkify shows the error: Must only contain lowercase ASCII letters.

**Comment by nfrasser** [comment]
Fixed in latest [v4 release](https://github.com/Hypercontext/linkifyjs/releases/tag/v4.0.0).
