### ISSUE TITLE
3 character custom scheme not is linkified

### ISSUE THREAD

**Issue by aaronraimist** [Hypercontext/linkifyjs#378]
Using v4.0.0-beta.4

[`geo`](https://en.wikipedia.org/wiki/Geo_URI_scheme) doesn't work as a custom scheme but custom schemes that are 4 characters or longer do work

**Comment by nfrasser** [comment]
Fixed in the latest [v4 release](https://github.com/Hypercontext/linkifyjs/releases/tag/v4.0.0).
