### ISSUE TITLE
Extra ; when whitespace after html-coded char (linkify-html)

### ISSUE THREAD

**Issue by gabooo** [Hypercontext/linkifyjs#396]
I have noticed that if the string to be linkified contains html encoded chars the removal of the coded sequence acts strangely. Here is an example:

Original string: &quot;https://www.google.com&quot;&quot;http://www.cloudera.com&quot;
Output: "https://www.google.com""http://www.cloudera.com";

Notice the ; at the end. That should not be there. If i add a space between the 2 ", there is a new ; before the space.

Original string: &quot;https://www.google.com&quot; &quot;http://www.cloudera.com&quot;
Output: "https://www.google.com"; "http://www.cloudera.com";

To me it seems like that if there is a whitespace after an HTML encoded char sequence, the removal of the char code (like &quot;) leaves the last char there.

**Comment by nfrasser** [comment]
Fixed in [latest v4 release](https://github.com/Hypercontext/linkifyjs/releases/tag/v4.0.0).
