### ISSUE TITLE
linkify.tokenize can not identify '//123' as a link

### ISSUE THREAD

**Issue by shengxiao3587** [Hypercontext/linkifyjs#401]
when '//123' is wrapped by Linkify component, it can identify as a link. But when i use linkify.tokenize to handle '//123', it will be identified as a text

**Comment by shengxiao3587** [comment]
hi, pls check https://codesandbox.io/s/flamboyant-jasper-46vws7?file=/src/App.js

**Comment by shengxiao3587** [comment]
I think i find the reason, for 2.x.x version '//123' will be identified as a url and for 3.x.x version '//123' will be identified as a text, correct me if anything wrong

**Comment by nfrasser** [comment]
@shengxiao3587 yes based on the example (which seems to use linkify v2), it looks like you're mixing multiple major version of linkify. Please be sure to use the same major versions of `linkifyjs` and `linkify-react`:

```js
"linkifyjs": "^4.0.0",
"linkify-react": "^4.0.0",
```

The text `//123` is not expected to be a valid link
