### ISSUE TITLE
React duplicate key warning with `nl2br: true` and two child strings

### ISSUE THREAD

**Issue by aeharding** [Hypercontext/linkifyjs#402]
Hello! Great library. Please let me know if you have any questions on this bug!

Note: This also occurred in v3 (with a different key name in the error).

# Repro
```ts
const opts = { nl2br: true };

const foo = `hello

`;
const bar = `hello

`;

const App = () => (
  <Linkify options={opts}>
    {foo} {bar}
  </Linkify>
);
```

Codesandbox: https://codesandbox.io/s/react-testing-library-demo-forked-tlok5c?file=/src/index.js

## Expected result

No duplicate key warning. (Everything seems to be fine other than the warning in the console.)

**Comment by nfrasser** [comment]
Hi @aeharding, thanks for reporting, should be fixed in the latest v4.0.1 release
