### ISSUE TITLE
Documentation looks wrong.

### ISSUE THREAD

**Issue by yuki-kawachi777** [Hypercontext/linkifyjs#405]
The documentation appears to be incorrect regarding the "options/target" description.
https://linkify.js.org/docs/options.html

> Default: '_blank' for URLs, null for everything else

As seen in CHANGELOG.md below, remove default target="_blank" attribute for discovered URLs. 
https://github.com/Hypercontext/linkifyjs/blob/bfacfeb638d6e7ae6599dc03615fa992c5c057bd/CHANGELOG.md#v300

If the documentation is wrong, you may want to fix it.

**Comment by nfrasser** [comment]
@yuki-kawachi777, thanks for reporting, made the fix, should be live shortly
