### ISSUE TITLE
How to use the hashtag module with the Linkify React component?

### ISSUE THREAD

**Issue by jordymeow** [Hypercontext/linkifyjs#411]
Hi,

I am loading the plugin like this:

`import hashtag from 'linkify-plugin-hashtag';`

But that doesn't linkify hashtags at all. I tried using all the options but to no avail:

```
<Linkify properties={{ target: '_blank', 
	formatHref: { hashtag: (href) => "https://twitter.com/hashtag/" + href.substr(1) },
	hashtag: ({ attributes, content }) => {
		const { href, ...props } = attributes;
		return <a to={href} {...props}>HASHTAG {content}</a>;
	} }}>
	{selectedSpot.description}
</Linkify>
```

I have also tried using options instead of properties (since there are some examples in the docs using options), but when I do so, my "target" (for normal links) stops working. For me, the documentation is a bit confusing and the React module doesn't really work the same way as the standard script.

Can you help me? Thanks a lot :)

**Comment by nfrasser** [comment]
@jordymeow hashtags should be working if you include the plugin, here's a reference implementation: https://codesandbox.io/s/linkify-react-testing-lus9w?file=/src/App.js

Note that you should be using `<Linkify options={...}>`, not `<Linkify properties={...}>` as [noted in the docs](https://linkify.js.org/docs/linkify-react.html#usage)

If you're still running into trouble, check the console for any warnings and make sure you import the hashtag plugin before you create a `<Linkify>` component for the first time. You may also need to check your NPM packages to see if you have multiple copies of `linkifyjs` installed. You can do so with the following command:

```sh
npm why linkifyjs
```
