### ISSUE TITLE
`registerCustomProtocol` breaks e-mail linkification

### ISSUE THREAD

**Issue by t3chguy** [Hypercontext/linkifyjs#414]
Using `registerCustomProtocol("matrix", true);` causes `matrix@example.com` to not be linkified as an email, instead only `example.com` get linkified. 

Downstream issue https://github.com/vector-im/element-web/issues/23806
Possibly related https://github.com/Hypercontext/linkifyjs/issues/410

**Comment by hanazuki** [comment]
It seems the same problem happens for the predefined protocols such as `http` and `mailto`, that is, `http@example.com` is not linkified as email. I just submitted a pull request to fix this issue: https://github.com/Hypercontext/linkifyjs/pull/417
