### ISSUE TITLE
Small footprint (~30kB minified, ~15kB gzipped) ?

### ISSUE THREAD

**Issue by bacloud23** [Hypercontext/linkifyjs#416]
Hi, Thanks a lot for proving *LinkifyJS* it is indeed a very bright solution.

Although I don't think of 30kb as small footprint when used on the browser. To my understanding this is a String manipulation library, nothing more, so what makes it up to 30kb ??

If I only import the followings `linkifyjs linkify-html`, is it 30kb ?

if yes, is it React and jQuery support ? the plugin system ? or something else that makes the bundle that big.

If these are optional, and easy to remove in a peer bundle, that would be very much appreciated.

Thanks a lot !!!!! 

edit:
These are some popular libraries and frameworks to have a relative estimate of why I think this is a huge bundle for what it does:

- react@18.2.0 => 6.4 kB Minified
- eta@1.12.3 => 5.7 kB Minified

**Comment by bacloud23** [comment]
I found out the source maybe of the problem, which is [this file](https://github.com/Hypercontext/linkifyjs/blob/main/packages/linkifyjs/src/tlds.js)

A solution might be a simple [Trie data structure](https://en.wikipedia.org/wiki/Trie). This is a simpler implementation of my own:
https://gist.github.com/bacloud23/ed2ca1c948383158dfb6ecb8f43af2ed

As I couldn't reason about Trie structure for now. You can see in fact it generated into a little bigger size and not lower, but I'm totally sure it can easily be tuned for its aim.

**Comment by bacloud23** [comment]
@nfrasser thanks a lot for considering this.

**Comment by nfrasser** [comment]
@bacloud23 thanks for the suggestion and for providing that sample code! You're right that the TLDs take up a significant amount of space. Other factors that increase file size include constructions of the URL state machines, options parsing, and regular-expressions for internationalized domain names.

I used a different trie implementation from the one you suggested. It reduces the amount of space the TLDs take up by around 3kB. Along with dropping support for some older browsers, the minified bundle size will now be around 19kB (10kB gzipped).

**Comment by nfrasser** [comment]
Addressed in v4.1.0

**Comment by bacloud23** [comment]
> I used a different trie implementation from the one you suggested. It reduces the amount of space the TLDs take up by around 3kB. Along with dropping support for some older browsers, the minified bundle size will now be around 19kB (10kB gzipped).

So impressed :) I will try to understand how you implemented that. I did not yet see code, but is that the regular Trie structure algorithm ? It is indeed very strong for repeating embedded Strings like natural language worlds.

Anyway, thanks, much gain,
