### ISSUE TITLE
Recommended approach to use async/await in `formatHref`

### ISSUE THREAD

**Issue by shubhendumadhukar** [Hypercontext/linkifyjs#424]
I am trying to use a custom logic to utilise mention plugin, wherein I want to check if the mentioned user exists by making an API call and format the link based on the results. I am unable to get it working.
```javascript
const options = {
    formatHref: {
      mention: async (href) => {
        const user = await getProfileByUsername(href);
        if (user) {
          return "/profiles" + href;
        }
      },
    },
    target: "_blank",
  };
```
This results in `<a href="[object Promise]" target="_blank">@test</a>`. How do I go about implementing an async function for this use case?

**Comment by nfrasser** [comment]
Hi @shubhendumadhukar, async functions are not currently supported for options and it would be difficult to safely implement in linkifyjs.

As a workaround, I'd suggest writing a custom interface with an async render loop. How exactly you do this depends on which interface you're using (string, React, etc.).

Here's an example with a modified linkify-string ([compared to original implementation](https://github.com/Hypercontext/linkifyjs/blob/ba048e02054ee97777c61d107ec7754bba7460ce/packages/linkify-string/src/linkify-string.js)):

```js
import { tokenize, Options } from 'linkifyjs';

function escapeText(text) {
	return text
	.replace(/&/g, '&amp;')
	.replace(/</g, '&lt;')
	.replace(/>/g, '&gt;');
}

function escapeAttr(href) {
	return href.replace(/"/g, '&quot;');
}

function attributesToString(attributes) {
	const result = [];
	for (const attr in attributes) {
		let val = attributes[attr] + '';
		result.push(`${attr}="${escapeAttr(val)}"`);
	}
	return result.join(' ');
}

function defaultRender({ tagName, attributes, content }) {
	return `<${tagName} ${attributesToString(attributes)}>${escapeText(content)}</${tagName}>`;
}

async function linkifyString(str, opts = {}) {
	opts = new Options(opts, defaultRender);

	const tokens = tokenize(str);
	const result = [];

	for (let i = 0; i < tokens.length; i++) {
		const token = tokens[i];
		if (token.t === 'mention') {
			// validate username
			const user = await getProfileByUsername(href);
			if (user) {
				result.push(opts.render(token));
			} else {
				result.push(escapeText(token.toString()));
			}
		} else if (token.t === 'nl' && opts.get('nl2br')) {
			result.push('<br>\n');
		} else if (!token.isLink || !opts.check(token)) {
			result.push(escapeText(token.toString()));
		} else {
			result.push(opts.render(token));
		}
	}

	return result.join('');
}
```

Usage:
```js
const options = {
  formatHref: {
    mention: (href) => "/profiles" + href
  },
  target: "_blank",
};
await linkifyString(data, options);
```

**Comment by shubhendumadhukar** [comment]
Thanks for helping with an example @nfrasser, I was able to implement this for linkify-html.

**Comment by alexgleason** [comment]
For sure the best thing to do, instead of reimplementing `linkifyStr`, is to just call `linkify.find()` to do a first pass, loop the results and fetch the data you need into a local map, and then call `linkifyStr` with your custom render functions in the closure. Yes you have to process the content twice, but it's way more ergonomic and less fragile.
