### ISSUE TITLE
Domains containing Unicode codepoints not fully recognized even if protocol is included

### ISSUE THREAD

**Issue by pludi** [Hypercontext/linkifyjs#427]
# Steps to reproduce

In any chat include a URL containing Unicode codepoints outside alphabets. This was noticed with the URL [http://↑↑↓↓←→←→ba.tk/](http://xn--ba-rzuadaibfa.tk/)

# Outcome
## What did you expect?

URL getting rendered as [http://↑↑↓↓←→←→ba.tk/](http://xn--ba-rzuadaibfa.tk/)
## What happened instead?

URL getting rendered as `http://↑↑↓↓←→←→`[ba.tk/](http://ba.tk/) (Escaped here to prevent Github from rendering it)

Example:
![image](https://user-images.githubusercontent.com/2112148/212649020-499a15ce-3446-45df-9a26-e76d434a5b87.png)

Possibly similar to #92

**Comment by pludi** [comment]
Ideally, anything between a valid protocol (`http`, `https`, `ftp`, `mailto`, …) and the next whitespace should be interpreted as an URI.

**Comment by nfrasser** [comment]
@pludi thanks for reporting, will look into this in the next few days

**Comment by nfrasser** [comment]
Fixed in latest release v4.1.1
