### ISSUE TITLE
Maybe it's an error, I don't know (Nextjs)

### ISSUE THREAD

**Issue by hugonascimento** [Hypercontext/linkifyjs#438]
Error when I get a JSON response with {styles.center}
I think you shouldn't create a link.

**Comment by hugonascimento** [comment]
I'm getting a JSON with texts, codes and links
I'm using linkifyjs to check if there are any htttp, https and email links, but I also get javascript codes in that JSON.
Every time I get a javascript code that has string.string it creates a link, example:
  <Box className={styles.center}>... (link in styles.center)
{messages.map((messages, key).... (link in messages.map)

**Comment by nfrasser** [comment]
Linkify is not meant to run on input that contains JavaScript code, only plain text or HTML. Both `.center` and `.map` are [top -level domains](https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains) so Linkify interprets them both as links.

There are a few ways to work around this:
- Pre-process your input to remove HTML/JavaScript entities before passing it into Linkify 
- Use [the DOM element interface](https://linkify.js.org/docs/linkify-element.html) to linkify your input _after_ it has been rendered to the page. For example:
```js
import linkifyElement from 'linkify-element'
import { useRef, useEffect } from 'react'

const Component = ({ data }) => {  // data is a rendered 
    const ref = useRef(null)
    useEffect(() => {
        linkifyElement(ref.current)
    }, [data])
    return <div ref={ref} dangerouslySetInnerHTML={{__html: data}} />
}

```
Note that this might not place nicely with React
- Use [the `validate` option](https://linkify.js.org/docs/options.html#validate) to filter out "invalid" links

I can't say what the best strategy is without knowing the use cases for your app and how exactly you are using Linkify.
