### ISSUE TITLE
Question:I want to match a link from a string that does not contain spaces

### ISSUE THREAD

**Issue by W1llQAQ** [Hypercontext/linkifyjs#446]
Now I use the version is 4.1.1

For example：
![Screenshot 2023-07-26 at 11 36 54](https://github.com/Hypercontext/linkifyjs/assets/84501845/4d7b0321-d182-4b22-a5f6-886c50e38f71)

I want to match the link from the first string, but the whole string is recognized as a link

**Comment by nfrasser** [comment]
Hi @W1llQAQ, apologies for the delay. Unfortunately it's very difficult for Linkify's current parser implementation to support the first case ([see discussion here for details](https://github.com/Hypercontext/linkifyjs/issues/351#issuecomment-937393153)). I have no plans to fix this at this time.
