### ISSUE TITLE
Query string of a URL isn't parsed

### ISSUE THREAD

**Issue by denno020** [Hypercontext/linkifyjs#448]
Linkify doesn't parse a query string when `https://` isn't included.

For example, the following string, "https://linkify.js.org?query=1"

Will parse to the URL of, `https://linkify.js.org?query=1`.

But this next string, "linkify.js.org?query=1"

Will parse to the URL of, `linkify.js.org`.

Not sure if the library has done this by design or not, but I feel like it would be nice if it did parse the query string too - it would absolutely help my use case of the package

**Comment by nfrasser** [comment]
@denno020 this is expected behaviour, the URL must have a `/` before the `?` to be considered valid. `linkify.js.org/?query=1` will be detected.

**Comment by denno020** [comment]
Thanks for the response @nfrasser, interesting that the library would choose to implement it that way though.. `linkify.js.org?query=1` is a perfectly valid URL, and arguably the most commonly used way of typing query strings.. The slash is very rarely used.. Is there a reason for requiring the slash before the question mark?

**Comment by denno020** [comment]
@nfrasser Just wanted to follow up on this. The slash being before the question mark to be considered valid, is that a library choice, or do I have a complete mis-understanding of how URL's work on the web?
