### ISSUE TITLE
How to use the `validate` function with `find`? Doesn't seem to be working!

### ISSUE THREAD

**Issue by rfgamaral** [Hypercontext/linkifyjs#450]
Hi there,

I'm trying to use the `validate` function with `find`, but it doesn't seem to be working:

```js
import { find } from 'linkifyjs'

const content = `[GitHub](https://github.com)

[Linkify](https://linkify.js.org "Linkify: a JS plugin by Hypercontext")`

const testA1 = find(content, {
  validate: false
})

const testA2 = find(content, {
  validate: () => false
})

const testA3 = find(content, {
  validate: {
    url: () => false
  }
})

const testB1 = find(content, 'url', {
  validate: false
})

const testB2 = find(content, 'url', {
  validate: () => false
})

const testB3 = find(content, 'url', {
  validate: {
    url: () => false
  }
})

console.log(testA1, testA2, testA3)
console.log(testB1, testB2, testB3)
```

**Output:**

![image](https://github.com/Hypercontext/linkifyjs/assets/96476/4608ebdf-6dd4-4ef2-89e0-6c557fdca126)

**CodeSandbox:**

- https://codesandbox.io/s/beautiful-grothendieck-6h2v5c?file=/src/index.mjs

Am I using it wrong, or is there an issue somewhere?

**Comment by nfrasser** [comment]
@rfgamaral thanks for reporting, this is a bug in the `find` function. Will fix this to the next release. In the mean time, you can try `.filter()` or something similar on the result of `.find()` to further filter out matches

**Comment by rfgamaral** [comment]
@nfrasser Do you have any other workaround that would work for my use case?

**Comment by nfrasser** [comment]
@rfgamaral apologies for the delay, this is now working with the latest Linkify v4.1.2

**Comment by rfgamaral** [comment]
Thank you, @nfrasser.
