### ISSUE TITLE
[BUG] attributes function receive modified/formatted href

### ISSUE THREAD

**Issue by ryaa** [Hypercontext/linkifyjs#452]
This https://github.com/Hypercontext/linkifyjs/issues/433 does not seem to be fixed in v4.1.1

**Comment by nfrasser** [comment]
@ryaa, I cannot reproduce this, can you share a code snippet that shows this bug?

**Comment by ryaa** [comment]
I'm sorry, the problem has been fixed. I have just upgraded _linkify-string_ to the latest version and it was still using old version of the _linkifyjs_ peer dependency. When I explicitly installed the latest version _linkifyjs_, the problem is gone.

**Comment by nfrasser** [comment]
@ryaa thanks for the update!
