### ISSUE TITLE
&hellip; is not properly handled

### ISSUE THREAD

**Issue by gravelfox** [Hypercontext/linkifyjs#455]
The ampersand in `&hellip;` is re-encoded, which doesn't seem to happen for other html encoded characters, for example the output of:

> LinkifyHtml("\<p\>Here is a link and an extra space: google.com \&nbsp;\<\/p\>\<p\>Here is a link and a greater-than: google.com \&gt;\<\/p\>\<p\>Here is a link and an ellipsis: google.com \&hellip;\<\/p\>");

is:

> <p>Here is a link and an extra space: <a href="https://www.google.com">google.com</a> &nbsp;</p><p>Here is a link and a greater-than: <a href="http://google.com">google.com</a> &gt;</p><p>Here is a link and an ellipsis: <a href="http://google.com">google.com</a> &amp;hellip;</p>

This means that while everything else I render as html looks right, an ellipsis ends up looking like `&hellip;`

I'd love to know if I'm doing something wrong here.

Thanks!

**Comment by gravelfox** [comment]
Coming back to this, I have found that this happens for almost all encoded symbols. I will write some workaround function to take care of this in the meantime unless anyone can tell me what I'm doing wrong. As far as I can tell, the only encoded symbols that work are the five in @nfrasser/simple-html-tokenizer/src/generated/html5-named-char-refs.ts, though I haven't taken the time to determine whether that is what is making them work...

**Comment by nfrasser** [comment]
Hi @gravelfox, thanks for reporting. This should be fixed in the latest v4.1.3

**Comment by gravelfox** [comment]
Rad, thank you! I am not proud of how hacky my workaround was and will be very happy to back it out!
