### ISSUE TITLE
SyntaxError: invalid identity escape in regular expression

### ISSUE THREAD

**Issue by atomiomi** [Hypercontext/linkifyjs#456]
I'm getting the following error in Firefox 
```
SyntaxError: invalid identity escape in regular expression
```

Error is originated here
<img width="652" alt="Screenshot 2023-11-01 at 22 36 44" src="https://github.com/Hypercontext/linkifyjs/assets/9496650/61852c54-2d3f-400f-b1ba-87eb24462ac9">

I'm using `linkify-html@4.1.0`.

Old Firefox browsers don't support all regex features, but I wanted to check if you're planning to fix it or linkify library doesn't support old browsers.

**Comment by nfrasser** [comment]
Hi @atomiomi, support for older browsers was dropped intentionally in v4.1 to reduce the bundle size. v4.0 versions still have support for this. If you'd like to keep using v4.1+, I suggest using a transpiler like Babel
