### ISSUE TITLE
how to avoid detecting as link that start with 123http?

### ISSUE THREAD

**Issue by zuizuihao** [Hypercontext/linkifyjs#467]
when I test "123http://google.com", but in our scenario, this should not be recognized as a link. the result better to be 123http://google.com. any solution to avoid detect as link?
```javascript
var htmlLinkify = linkifyHtml("123http://google.com");
console.log(htmlLinkify); //123<a href="http://google.com">http://google.com</a>
```

**Comment by zuizuihao** [comment]
test mailto:google.com
test 123mailto:google.com

**Comment by zuizuihao** [comment]
test mailto:111@11.com
test 123http://google.com/

**Comment by zuizuihao** [comment]
test 123mailto:111@11.com

**Comment by txdv** [comment]
use https://linkify.js.org/docs/options.html#validate
