### ISSUE TITLE
linkify-html doesn't add className or other attributes to existing anchor tags

### ISSUE THREAD

**Issue by donghoon-song** [Hypercontext/linkifyjs#483]
I am using it in my project. I found that it doesn't add 'className' option so I created a reproduction code. I used 'linkify-html' cuz it's html string but doesn't work in some cases. I don't know the specific cause.

### reproduction
https://codesandbox.io/p/sandbox/epic-meninsky-w645vr?file=%2Fsrc%2Findex.js%3A10%2C80

**Comment by nfrasser** [comment]
Hi @donghoon-song, I'm getting a "Sandbox not found" message. Could you please check the permissions in codesandbox to make sure it has public access?

**Comment by donghoon-song** [comment]
@nfrasser Sorry. I've updated it :)
https://codesandbox.io/p/devbox/58rq5l?migrateFrom=w645vr

**Comment by nfrasser** [comment]
Okay, I can see it now. So, to be clear, given the following input:

```js
linkifyHtml('<div>hello <a href="https://google.com">google.com</a></div><a href="https://www.w3schools.com">Visit W3Schools.com!</a>', {className: 'aaa'})
```

Do you expect the following output?

```html
<div>hello <a href="https://google.com" class="aaa">google.com</a></div><a href="https://www.w3schools.com" class="aaa">Visit W3Schools.com!</a>
```

**Comment by donghoon-song** [comment]
@nfrasser Yes I do!

**Comment by nfrasser** [comment]
Okay understood, unfortunately this kind of functionality is outside the scope of Linkify's functionality: Linkify is meant to find new links and wrap them with `<a>` tags. It is not meant to adjust existing HTML or links.

I assume you need to add a class to all `<a>` tags to apply CSS styling? Could you instead make a CSS rule that applies to all anchor tags? For example:

```jsx
function App() {
  const html =' ...'
  return (
    <div className="linkified" dangerouslySetInnerHTML={{ __html: linkifyHtml(html) }}>
  )
}
```

```css
.linkified a {
    /* insert CSS rules here */
}
```

**Comment by donghoon-song** [comment]
@nfrasser Okay I see it is outside the scope. Thank you for your quick answer :)
I'd rather leave only links in html. I have to show the html from admin DB and it is also better to allow for the people who use an admin to write just links rather than whole a tags.
