### ISSUE TITLE
ws and wss suport for test method

### ISSUE THREAD

**Issue by jhercog** [Hypercontext/linkifyjs#484]
Right now `linkify.test('wss://example.com/event')` returns false.
Also, there is no 'type' argument for testing against WebSocket urls.

Please validate urls with wss/ws scheme as true or include the type argument which would make it so
E.g. `linkify.test('wss://example.com/event', 'websocket')` or similar.

**Comment by nfrasser** [comment]
@jhercog thanks for reporting, this should work if you [register `wss` as a custom protocol](https://linkify.js.org/docs/linkifyjs.html#linkifyregistercustomprotocol-scheme--optionalslashslash--false) before calling `test`:

```js
linkify.registerCustomProtocol('wss');
linkify.test('wss://example.com/event') // true
```

Note that you only need to call this once for the lifetime of your script, e.g., right after importing Linkify.

**Comment by jhercog** [comment]
@nfrasser Thank you for the info, it is just what i need.
