### ISSUE TITLE
Create a Security Policy and/or Enable Private Vulnerability Reporting

### ISSUE THREAD

**Issue by hunterverhelst** [Hypercontext/linkifyjs#486]
I have discovered a security vulnerability in this package and would like to report it. Please create a `SECURITY.md` file containing instructions on how to report a security vulnerability. See [here](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) for more information.

GitHub also provides a way to directly report security vulnerabilities that can be enabled for each repository. See [here](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) for instructions on how to do so.

**Comment by nfrasser** [comment]
Hi @hunterverhelst, I've enabled private reporting, please go ahead with your submission: https://github.com/Hypercontext/linkifyjs/security
