### ISSUE TITLE
how do you enforce .find to require a protocol for strings that aren't emails?

### ISSUE THREAD

**Issue by fridaystreet** [Hypercontext/linkifyjs#491]
I've just noticed in our editor that uses linkify to find links in typed or pasted text, that the library by default is returning that a string with a dot (and no protocol) in it is a valid url if the chars after the text are a valid tld.

Is there an option to disable this? I noticed in another library linkify-it, it has an option to disable fuzzyUrl matching which measn no protocol strings.

try the basic example below

```js

const simpleStr = 'node.id'
const { find } = require('linkifyjs')
console.log(find(simpleStr))

\\returns
[
  {
    type: 'url',
    value: 'node.id',
    isLink: true,
    href: 'http://node.id',
    start: 0,
    end: 7
  }
]
```

Any assitance would be greatly appreciated. Thanks

**Comment by nfrasser** [comment]
@fridaystreet try the `validate` option:

```js
find(simpleStr, {
  validate: {
    url: (value) => /^https?:\/\//.test(value),
  },
})
```
