### ISSUE TITLE
Emoji and Internationalized Domain Names should be hyperlinked

### ISSUE THREAD

**Issue by dandv** [Hypercontext/linkifyjs#92]
[Example](https://github.com/ali-saleem/anchorme.js/issues/1): www.🍕💩.ws - GitHub does it correctly!

![image](https://cloud.githubusercontent.com/assets/33569/11670599/afee43be-9db7-11e5-9673-e1ae93c5b212.png)

**Comment by cawa-93** [comment]
In my opinion to handle the characters emotions as the link is not correct. This may cause some mistakes if the text contains both the link and choose emotions. And in the plugin everything works correctly.

**Comment by nfrasser** [comment]
@dandv I've been looking to add this functionality in the form of a plugin. Will update here when we have support for it.

**Comment by maxisme** [comment]
Any updates?

**Comment by Amareis** [comment]
Heeeey, any progress on it? Can we make a plugin for Unicode (not Punycode) domains?

**Comment by joonhocho** [comment]
Hashtag should also accept unicode characters, for example, #한글 should be linkified as it's valid Korean. same goes for all non-alphabet characters.

**Comment by nfrasser** [comment]
Hi all, thanks for your many years of patience on this one! 

Internationalized domain support is officially in development and is now available for preliminary testing the the latest `v3.0.0-beta.1`. A production release coming soon. 

If you can, please try it out and report any bugs you find

**Comment by nfrasser** [comment]
Fixed in v3
